# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(901, 638)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    color: rgb(190, 232, 240);\n"
"    font: 20px \"Segoe UI\";\n"
"}\n"
"\n"
"#frame{\n"
"background-color: rgb(33, 37, 43);\n"
"}\n"
"\n"
"#page_0{\n"
"background-color: rgb(47, 62, 69);\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"}\n"
"#page_1{\n"
"background-color: rgb(33, 37, 43);\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"}\n"
"#page_2{\n"
"background-color: rgb(33, 37, 43);\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"}\n"
"#page_4{\n"
"background-color: rgb(47, 62, 69);\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"}\n"
"#DockPage{\n"
"background-color: rgb(33, 37, 43);\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"}\n"
"#ViewResiduePage{\n"
"background-color: rgb(33, 37, 43);\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"}\n"
"#page_5{\n"
"background-color: rgb(47, 62, 69);\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"}\n"
"#leftmenu{\n"
"background-color: rgb(33, 37, 43);\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Tooltip */\n"
"QToolTip {\n"
"    color: #ffffff;\n"
"    background-color: rgba(33, 37, 43, 180);\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"    background-image: none;\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 2px solid rgb(255, 121, 198);\n"
"    text-align: left;\n"
"    padding-left: 8px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Bg App */\n"
"#bgApp {    \n"
"    background-color: rgb(40, 44, 52);\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Left Menu */\n"
"\n"
"\n"
"#titleLeftApp { font: 63 12pt \"Segoe UI Semibold\"; }\n"
"#titleLeftDescription { font: 8pt \"Segoe UI\"; color: rgb(189, 147, 249); }\n"
"\n"
"/* MENUS */\n"
"\n"
"#leftMenuFrame{\n"
"    border-top: 3px solid rgb(44, 49, 58);\n"
"}\n"
"\n"
"/* Toggle Button */\n"
"#toggleButton {\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 20px solid transparent;\n"
"    background-color: rgb(47, 62, 69);\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"    color: rgb(113, 126, 149);\n"
"}\n"
"#toggleButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#toggleButton:pressed {\n"
"    background-color: rgb(189, 147, 249);\n"
"}\n"
"\n"
"/* Title Menu */\n"
"#titleRightInfo { padding-left: 10px; }\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Extra Tab */\n"
"#extraLeftBox {    \n"
"    background-color: rgb(44, 49, 58);\n"
"}\n"
"#extraTopBg{    \n"
"    background-color: rgb(189, 147, 249)\n"
"}\n"
"\n"
"\n"
"/* Label */\n"
"#extraLabel { color: rgb(255, 255, 255); }\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"LineEdit */\n"
"QLineEdit {\n"
"    background-color: rgb(33, 37, 43);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(33, 37, 43);\n"
"    padding-left: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"PlainTextEdit */\n"
"QPlainTextEdit {\n"
"    background-color: rgb(47, 62, 69);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(33, 37, 43);\n"
"    padding: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"}\n"
"QPlainTextEdit  QScrollBar:vertical {\n"
"    width: 8px;\n"
" }\n"
"QPlainTextEdit  QScrollBar:horizontal {\n"
"    height: 8px;\n"
" }\n"
"QPlainTextEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ScrollBars */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 8px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(189, 147, 249);\n"
"    min-width: 25px;\n"
"    border-radius: 4px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(0, 0, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(190, 232, 240);\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CheckBox */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/icons/images/icons/cil-check-alt.png);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"RadioButton */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ComboBox */\n"
"QComboBox{\n"
"    background-color:rgb(244, 238, 226);\n"
"\n"
"    border-radius: 5px;\n"
"    border: 4px solid rgb(33, 37, 43);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"color:rgb(0, 170, 127);\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    \n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(255, 121, 198);    \n"
"    background-color: rgb(33, 37, 43);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Button */\n"
"QPushButton {\n"
"    border: 2px solid rgb(52, 99, 72);\n"
"    border-radius: 3px;    \n"
"    border-style:double;\n"
"    background-color: rgb(47, 62, 69);\n"
"    border-width:1px\n"
"}\n"
"QPushButton:hover {\n"
"/*    background-color: rgb(57, 65, 80);*/\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"    border-style:double;\n"
"    background-color: rgb(191, 207, 228);\n"
"\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(197, 233, 199);\n"
"    border-style:double;\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.TotalWidget = QtWidgets.QWidget(self.centralwidget)
        self.TotalWidget.setGeometry(QtCore.QRect(10, 20, 830, 511))
        self.TotalWidget.setMinimumSize(QtCore.QSize(830, 511))
        self.TotalWidget.setMaximumSize(QtCore.QSize(830, 511))
        self.TotalWidget.setObjectName("TotalWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.TotalWidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.LeftBox = QtWidgets.QWidget(self.TotalWidget)
        self.LeftBox.setMinimumSize(QtCore.QSize(101, 511))
        self.LeftBox.setMaximumSize(QtCore.QSize(101, 511))
        self.LeftBox.setStyleSheet("QLabel{\n"
"    border-width:2px 5px 10px 15px;\n"
"    border-width:2px 10px;  // 上下  左右\n"
"    border-style:solid;\n"
"    border-color:red;\n"
"}")
        self.LeftBox.setObjectName("LeftBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.LeftBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 9)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Logo = QtWidgets.QFrame(self.LeftBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Logo.sizePolicy().hasHeightForWidth())
        self.Logo.setSizePolicy(sizePolicy)
        self.Logo.setStyleSheet("background-color: rgb(47, 62, 69);")
        self.Logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Logo.setObjectName("Logo")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Logo)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Logolabel = QtWidgets.QLabel(self.Logo)
        self.Logolabel.setStyleSheet("background-color: rgb(47, 62, 69);")
        self.Logolabel.setObjectName("Logolabel")
        self.verticalLayout_6.addWidget(self.Logolabel)
        self.verticalLayout_2.addWidget(self.Logo)
        self.LeftMenu = QtWidgets.QFrame(self.LeftBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.LeftMenu.sizePolicy().hasHeightForWidth())
        self.LeftMenu.setSizePolicy(sizePolicy)
        self.LeftMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LeftMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LeftMenu.setObjectName("LeftMenu")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.LeftMenu)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.PredictPageButton = QtWidgets.QPushButton(self.LeftMenu)
        self.PredictPageButton.setObjectName("PredictPageButton")
        self.verticalLayout_5.addWidget(self.PredictPageButton)
        self.DockPageButton = QtWidgets.QPushButton(self.LeftMenu)
        self.DockPageButton.setObjectName("DockPageButton")
        self.verticalLayout_5.addWidget(self.DockPageButton)
        self.ViewResiduePageButton = QtWidgets.QPushButton(self.LeftMenu)
        self.ViewResiduePageButton.setObjectName("ViewResiduePageButton")
        self.verticalLayout_5.addWidget(self.ViewResiduePageButton)
        self.pushButton_6 = QtWidgets.QPushButton(self.LeftMenu)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_5.addWidget(self.pushButton_6)
        self.verticalLayout_2.addWidget(self.LeftMenu)
        self.horizontalLayout_7.addWidget(self.LeftBox)
        self.ContentBox = QtWidgets.QStackedWidget(self.TotalWidget)
        self.ContentBox.setMinimumSize(QtCore.QSize(715, 511))
        self.ContentBox.setObjectName("ContentBox")
        self.PredictPage = QtWidgets.QWidget()
        self.PredictPage.setObjectName("PredictPage")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.PredictPage)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame = QtWidgets.QFrame(self.PredictPage)
        self.frame.setMinimumSize(QtCore.QSize(711, 511))
        self.frame.setMaximumSize(QtCore.QSize(711, 511))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.NameLabel = QtWidgets.QLabel(self.frame)
        self.NameLabel.setObjectName("NameLabel")
        self.verticalLayout.addWidget(self.NameLabel)
        self.InputFrame = QtWidgets.QFrame(self.frame)
        self.InputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.InputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InputFrame.setObjectName("InputFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.InputFrame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.SequenceInput = QtWidgets.QFrame(self.InputFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.SequenceInput.sizePolicy().hasHeightForWidth())
        self.SequenceInput.setSizePolicy(sizePolicy)
        self.SequenceInput.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SequenceInput.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SequenceInput.setObjectName("SequenceInput")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.SequenceInput)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.AntigenLabel = QtWidgets.QLabel(self.SequenceInput)
        self.AntigenLabel.setObjectName("AntigenLabel")
        self.verticalLayout_4.addWidget(self.AntigenLabel)
        self.ABSplainTextEdit = QtWidgets.QPlainTextEdit(self.SequenceInput)
        self.ABSplainTextEdit.setObjectName("ABSplainTextEdit")
        self.verticalLayout_4.addWidget(self.ABSplainTextEdit)
        self.AntibodyLabel = QtWidgets.QLabel(self.SequenceInput)
        self.AntibodyLabel.setObjectName("AntibodyLabel")
        self.verticalLayout_4.addWidget(self.AntibodyLabel)
        self.AGSplainTextEdit = QtWidgets.QPlainTextEdit(self.SequenceInput)
        self.AGSplainTextEdit.setObjectName("AGSplainTextEdit")
        self.verticalLayout_4.addWidget(self.AGSplainTextEdit)
        self.horizontalLayout_4.addWidget(self.SequenceInput)
        self.AdbancedInput = QtWidgets.QFrame(self.InputFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AdbancedInput.sizePolicy().hasHeightForWidth())
        self.AdbancedInput.setSizePolicy(sizePolicy)
        self.AdbancedInput.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AdbancedInput.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AdbancedInput.setObjectName("AdbancedInput")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.AdbancedInput)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_3 = QtWidgets.QWidget(self.AdbancedInput)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget_3)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_9.addWidget(self.checkBox_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget_3)
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout_9.addWidget(self.comboBox_2)
        self.verticalLayout_7.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.AdbancedInput)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.checkBox = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_8.addWidget(self.checkBox)
        self.comboBox = QtWidgets.QComboBox(self.widget_2)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_8.addWidget(self.comboBox)
        self.verticalLayout_7.addWidget(self.widget_2)
        self.horizontalLayout_4.addWidget(self.AdbancedInput)
        self.verticalLayout.addWidget(self.InputFrame)
        self.SubmitFrame = QtWidgets.QFrame(self.frame)
        self.SubmitFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SubmitFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubmitFrame.setObjectName("SubmitFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.SubmitFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ButtonFrame = QtWidgets.QFrame(self.SubmitFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.ButtonFrame.sizePolicy().hasHeightForWidth())
        self.ButtonFrame.setSizePolicy(sizePolicy)
        self.ButtonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ButtonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ButtonFrame.setObjectName("ButtonFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.ButtonFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_choose_file = QtWidgets.QPushButton(self.ButtonFrame)
        self.btn_choose_file.setObjectName("btn_choose_file")
        self.horizontalLayout_3.addWidget(self.btn_choose_file)
        spacerItem = QtWidgets.QSpacerItem(156, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.SubmitButton = QtWidgets.QPushButton(self.ButtonFrame)
        self.SubmitButton.setObjectName("SubmitButton")
        self.horizontalLayout_3.addWidget(self.SubmitButton)
        spacerItem1 = QtWidgets.QSpacerItem(156, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.ViewButton = QtWidgets.QPushButton(self.ButtonFrame)
        self.ViewButton.setObjectName("ViewButton")
        self.horizontalLayout_3.addWidget(self.ViewButton)
        spacerItem2 = QtWidgets.QSpacerItem(156, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.ButtonFrame)
        self.ViewFrame = QtWidgets.QFrame(self.SubmitFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.ViewFrame.sizePolicy().hasHeightForWidth())
        self.ViewFrame.setSizePolicy(sizePolicy)
        self.ViewFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ViewFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ViewFrame.setObjectName("ViewFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.ViewFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.ViewFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet("background-color: rgb(47, 62, 69);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.AntigenViewPage = QtWidgets.QWidget()
        self.AntigenViewPage.setObjectName("AntigenViewPage")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.AntigenViewPage)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AGplainTextEdit = QtWidgets.QPlainTextEdit(self.AntigenViewPage)
        self.AGplainTextEdit.setStyleSheet("background-color: rgb(47, 62, 69);")
        self.AGplainTextEdit.setObjectName("AGplainTextEdit")
        self.horizontalLayout.addWidget(self.AGplainTextEdit)
        self.stackedWidget.addWidget(self.AntigenViewPage)
        self.AntibodyViewPage = QtWidgets.QWidget()
        self.AntibodyViewPage.setObjectName("AntibodyViewPage")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.AntibodyViewPage)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ABplainTextEdit_4 = QtWidgets.QPlainTextEdit(self.AntibodyViewPage)
        self.ABplainTextEdit_4.setObjectName("ABplainTextEdit_4")
        self.horizontalLayout_5.addWidget(self.ABplainTextEdit_4)
        self.stackedWidget.addWidget(self.AntibodyViewPage)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout_3.addWidget(self.ViewFrame)
        self.verticalLayout.addWidget(self.SubmitFrame)
        self.horizontalLayout_6.addWidget(self.frame)
        self.ContentBox.addWidget(self.PredictPage)
        self.ViewResiduePage = QtWidgets.QWidget()
        self.ViewResiduePage.setObjectName("ViewResiduePage")
        self.ViewResidueFrame = QtWidgets.QFrame(self.ViewResiduePage)
        self.ViewResidueFrame.setGeometry(QtCore.QRect(30, 30, 671, 450))
        self.ViewResidueFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ViewResidueFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ViewResidueFrame.setObjectName("ViewResidueFrame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.ViewResidueFrame)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.ViewLeftFrame = QtWidgets.QFrame(self.ViewResidueFrame)
        self.ViewLeftFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ViewLeftFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ViewLeftFrame.setObjectName("ViewLeftFrame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.ViewLeftFrame)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.ResearchFrame_l = QtWidgets.QFrame(self.ViewLeftFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.ResearchFrame_l.sizePolicy().hasHeightForWidth())
        self.ResearchFrame_l.setSizePolicy(sizePolicy)
        self.ResearchFrame_l.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ResearchFrame_l.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ResearchFrame_l.setObjectName("ResearchFrame_l")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.ResearchFrame_l)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.NameTextEdit_l = QtWidgets.QPlainTextEdit(self.ResearchFrame_l)
        self.NameTextEdit_l.setMinimumSize(QtCore.QSize(0, 30))
        self.NameTextEdit_l.setMaximumSize(QtCore.QSize(16777215, 30))
        self.NameTextEdit_l.setObjectName("NameTextEdit_l")
        self.horizontalLayout_10.addWidget(self.NameTextEdit_l)
        self.FindButton_l = QtWidgets.QPushButton(self.ResearchFrame_l)
        self.FindButton_l.setObjectName("FindButton_l")
        self.horizontalLayout_10.addWidget(self.FindButton_l)
        self.verticalLayout_11.addWidget(self.ResearchFrame_l)
        self.FliePlainTextEdit_l = QtWidgets.QPlainTextEdit(self.ViewLeftFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.FliePlainTextEdit_l.sizePolicy().hasHeightForWidth())
        self.FliePlainTextEdit_l.setSizePolicy(sizePolicy)
        self.FliePlainTextEdit_l.setObjectName("FliePlainTextEdit_l")
        self.verticalLayout_11.addWidget(self.FliePlainTextEdit_l)
        self.horizontalLayout_12.addWidget(self.ViewLeftFrame)
        self.ViewRightFrame = QtWidgets.QFrame(self.ViewResidueFrame)
        self.ViewRightFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ViewRightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ViewRightFrame.setObjectName("ViewRightFrame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.ViewRightFrame)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.ResearchFrame_r = QtWidgets.QFrame(self.ViewRightFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.ResearchFrame_r.sizePolicy().hasHeightForWidth())
        self.ResearchFrame_r.setSizePolicy(sizePolicy)
        self.ResearchFrame_r.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ResearchFrame_r.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ResearchFrame_r.setObjectName("ResearchFrame_r")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.ResearchFrame_r)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.NameTextEdit_r = QtWidgets.QPlainTextEdit(self.ResearchFrame_r)
        self.NameTextEdit_r.setMinimumSize(QtCore.QSize(0, 30))
        self.NameTextEdit_r.setMaximumSize(QtCore.QSize(16777215, 30))
        self.NameTextEdit_r.setObjectName("NameTextEdit_r")
        self.horizontalLayout_11.addWidget(self.NameTextEdit_r)
        self.FindButton_r = QtWidgets.QPushButton(self.ResearchFrame_r)
        self.FindButton_r.setObjectName("FindButton_r")
        self.horizontalLayout_11.addWidget(self.FindButton_r)
        self.verticalLayout_12.addWidget(self.ResearchFrame_r)
        self.FilePlainTextEdit_r = QtWidgets.QPlainTextEdit(self.ViewRightFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.FilePlainTextEdit_r.sizePolicy().hasHeightForWidth())
        self.FilePlainTextEdit_r.setSizePolicy(sizePolicy)
        self.FilePlainTextEdit_r.setObjectName("FilePlainTextEdit_r")
        self.verticalLayout_12.addWidget(self.FilePlainTextEdit_r)
        self.horizontalLayout_12.addWidget(self.ViewRightFrame)
        self.ContentBox.addWidget(self.ViewResiduePage)
        self.DockPage = QtWidgets.QWidget()
        self.DockPage.setObjectName("DockPage")
        self.DockInputFrame = QtWidgets.QFrame(self.DockPage)
        self.DockInputFrame.setGeometry(QtCore.QRect(30, 120, 541, 291))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.DockInputFrame.sizePolicy().hasHeightForWidth())
        self.DockInputFrame.setSizePolicy(sizePolicy)
        self.DockInputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DockInputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DockInputFrame.setObjectName("DockInputFrame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.DockInputFrame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_2 = QtWidgets.QFrame(self.DockInputFrame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.AntigenLabel_2 = QtWidgets.QLabel(self.frame_2)
        self.AntigenLabel_2.setObjectName("AntigenLabel_2")
        self.horizontalLayout_8.addWidget(self.AntigenLabel_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.AGLocalFindButton = QtWidgets.QPushButton(self.frame_2)
        self.AGLocalFindButton.setObjectName("AGLocalFindButton")
        self.horizontalLayout_8.addWidget(self.AGLocalFindButton)
        self.verticalLayout_10.addWidget(self.frame_2)
        self.DockABSplainTextEdit = QtWidgets.QPlainTextEdit(self.DockInputFrame)
        self.DockABSplainTextEdit.setObjectName("DockABSplainTextEdit")
        self.verticalLayout_10.addWidget(self.DockABSplainTextEdit)
        self.frame_3 = QtWidgets.QFrame(self.DockInputFrame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.AntigenLabel_3 = QtWidgets.QLabel(self.frame_3)
        self.AntigenLabel_3.setObjectName("AntigenLabel_3")
        self.horizontalLayout_9.addWidget(self.AntigenLabel_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.ABLocalFindButton = QtWidgets.QPushButton(self.frame_3)
        self.ABLocalFindButton.setObjectName("ABLocalFindButton")
        self.horizontalLayout_9.addWidget(self.ABLocalFindButton)
        self.verticalLayout_10.addWidget(self.frame_3)
        self.DockAGSplainTextEdit = QtWidgets.QPlainTextEdit(self.DockInputFrame)
        self.DockAGSplainTextEdit.setObjectName("DockAGSplainTextEdit")
        self.verticalLayout_10.addWidget(self.DockAGSplainTextEdit)
        self.DockSubmitButton = QtWidgets.QPushButton(self.DockPage)
        self.DockSubmitButton.setGeometry(QtCore.QRect(600, 260, 75, 23))
        self.DockSubmitButton.setObjectName("DockSubmitButton")
        self.ContentBox.addWidget(self.DockPage)
        self.horizontalLayout_7.addWidget(self.ContentBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 901, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.ContentBox.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Logolabel.setText(_translate("MainWindow", "LOGO"))
        self.PredictPageButton.setText(_translate("MainWindow", "Predict"))
        self.DockPageButton.setText(_translate("MainWindow", "Dock"))
        self.ViewResiduePageButton.setText(_translate("MainWindow", "FileView"))
        self.pushButton_6.setText(_translate("MainWindow", "menu4"))
        self.NameLabel.setText(_translate("MainWindow", "抗原抗体复合物预测"))
        self.AntigenLabel.setText(_translate("MainWindow", "Enter Query Sequence"))
        self.AntibodyLabel.setText(_translate("MainWindow", "Enter Query Sequence"))
        self.checkBox_2.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.btn_choose_file.setText(_translate("MainWindow", "fasta file"))
        self.SubmitButton.setText(_translate("MainWindow", "submit"))
        self.ViewButton.setText(_translate("MainWindow", "view"))
        self.FindButton_l.setText(_translate("MainWindow", "LocalFind"))
        self.FindButton_r.setText(_translate("MainWindow", "LocalFind"))
        self.AntigenLabel_2.setText(_translate("MainWindow", "Enter Query Sequence"))
        self.AGLocalFindButton.setText(_translate("MainWindow", "LocalFind"))
        self.AntigenLabel_3.setText(_translate("MainWindow", "Enter Query Sequence"))
        self.ABLocalFindButton.setText(_translate("MainWindow", "LocalFind"))
        self.DockSubmitButton.setText(_translate("MainWindow", "submit"))
